@startuml

show empty description
'scale 200*100
[*] --> INIT_BYTE_STATE

'IDLE_STATE :
'IDLE_STATE -d-> INIT_BYTE_STATE

INIT_BYTE_STATE : count_bit = 8
INIT_BYTE_STATE --> START_BIT_BYTE_STATE : new_byte_state == START_BIT_BYTE_STATE
INIT_BYTE_STATE --> INIT_BYTE_STATE

START_BIT_BYTE_STATE : SEVEN_SEG_DIO = low
START_BIT_BYTE_STATE --> SET_BIT_BYTE_STATE

SET_BIT_BYTE_STATE : if (value_in & 0x80)\n SEVEN_SEG_DIO = high\n else\n SEVEN_SEG_DIO = low\ncount_bit--
SET_BIT_BYTE_STATE --> NEW_BIT_BIT_BYTE_STATE

NEW_BIT_BIT_BYTE_STATE : value_in = value_in << 1
NEW_BIT_BIT_BYTE_STATE --> WAIT_BYTE_STATE

WAIT_BYTE_STATE :
WAIT_BYTE_STATE --> RELEASE_BIT_BYTE_STATE

RELEASE_BIT_BYTE_STATE : SEVEN_SEG_DIO = high
RELEASE_BIT_BYTE_STATE --> BYTE_SENT_BYTE_STATE : count_bit == 0
RELEASE_BIT_BYTE_STATE --> START_BIT_BYTE_STATE : count_bit != 0

BYTE_SENT_BYTE_STATE : new_byte_state = INIT_BYTE_STATE
BYTE_SENT_BYTE_STATE --> INIT_BYTE_STATE
'BYTE_SENT_BYTE_STATE --> [*]


@enduml

